/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LoopingSolutions;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        boolean expected = true;
        assertTrue(String.valueOf(expected), classUnderTest.someLibraryMethod());
    }
}
