language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
#solution: ./loopingKatasHome/dotnetcore/LoopingKatas.sln
script:
  - cd ./loopingKatasHome/dotnetcore/
  - dotnet restore
  - dotnet build