language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
#solution: ./loopingKatasHome/dotnetcore/LoopingKatas.sln
script:
  - cd /home/travis/build/jmacgregor-accenture/loopingKatasHome/dotnetcore/
  - dotnet restore
  - dotnet build
branches: 
  only:
  - master
  - development